# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kullanıcı_girişi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 553)
        MainWindow.setStyleSheet("\n"
"QLabel {\n"
"    color: #2c3e50;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"}\n"
"QPushButton {\n"
"    background-color: #a2ded0;\n"
"    color: black;\n"
"    border-radius: 8px;\n"
"    padding: 6px;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #7bdcb5;\n"
"}\n"
"QMainWindow {\n"
"    background-color: #fef5e7; /* Açık turuncu tonunda arka plan */\n"
"}\n"
"QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 4px;\n"
"    padding: 4px;\n"
"    font-size: 14px;\n"
"}\n"
"QGroupBox {\n"
"    border: 2px solid #f39c12;\n"
"    border-radius: 10px;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 4px;\n"
"    background-color: #f39c12;\n"
"    color: white;\n"
"    border-radius: 6px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.giriskullannigirii = QtWidgets.QLabel(self.centralwidget)
        self.giriskullannigirii.setGeometry(QtCore.QRect(130, 210, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.giriskullannigirii.setFont(font)
        self.giriskullannigirii.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.giriskullannigirii.setObjectName("giriskullannigirii")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 260, 381, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.giri_kullancad = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.giri_kullancad.setFont(font)
        self.giri_kullancad.setInputMask("")
        self.giri_kullancad.setText("")
        self.giri_kullancad.setMaxLength(20)
        self.giri_kullancad.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.giri_kullancad.setClearButtonEnabled(True)
        self.giri_kullancad.setObjectName("giri_kullancad")
        self.verticalLayout_2.addWidget(self.giri_kullancad)
        self.giri_sifre = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.giri_sifre.setFont(font)
        self.giri_sifre.setText("")
        self.giri_sifre.setMaxLength(20)
        self.giri_sifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.giri_sifre.setClearButtonEnabled(True)
        self.giri_sifre.setObjectName("giri_sifre")
        self.verticalLayout_2.addWidget(self.giri_sifre)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.giris = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.giris.setFont(font)
        self.giris.setObjectName("giris")
        self.verticalLayout_3.addWidget(self.giris)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 170, 47, 13))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 91, 261))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("images/logo.png.webp"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(530, 130, 91, 261))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("images/logo.png.webp"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.giriskullannigirii.setText(_translate("MainWindow", "Kullanıcı Girişi"))
        self.label.setText(_translate("MainWindow", "Kullanıcı Adı:"))
        self.label_2.setText(_translate("MainWindow", "Şifre:"))
        self.giri_kullancad.setPlaceholderText(_translate("MainWindow", "8-20 uzunluğuna kullanıcı adınızı giriniz."))
        self.giri_sifre.setPlaceholderText(_translate("MainWindow", "Şifrenizi giriniz."))
        self.giris.setText(_translate("MainWindow", "Giriş"))
